<a href="https://colab.research.google.com/github/JennyferSRodriguezH/Metodos--Numericos/blob/main/Muerte_En_La_Reserva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Instrucciones del problema:**



Durante una ronda de inspección por una reserva, dos guardabosques descubrieron
el cadáver de un jabalí. Un examen preliminar permitió concluir que el animal falleció instantáneamente a causa de un balazo de una cazador furtivo. sospechando que el cazador debía regresar a recoger su presa, los guardas decidieron esperarlo escondidos no lejos del lugar del crimen. Al poco tiempo aparecieron dos sujetos y se dirigieron sin rodeos al jabalí. Al ser detenidos los desconocidos negaron rotundamente su participación en el delito. Aunque los guardabosques tenían pruebas indirectas de su culpabilidad, para obtener una prueba fehaciente era necesario determinar el instante exacto en que el jabalí fue muerto.

Conforme a la ley de radiación de calor la velocidad de enfriamiento de un cuerpo en el medio ambiente es proporcionar a la diferencia. Entre la temperatura del cuerpo y la temperatura del medio


> $\frac{dx}{dt} = k(x-a)$



Donde x es la temperatura del cuerpo en el instante t, a es la temperatura del medio ambiente y k es un factor positivo de proporcionalidad, x0 es la temperatura del cuerpo en el instante $t = 0$.



*   (a) Si en el instante en que fueron detenidos los sospechosos la temperatura $x$ del cuerpo del jabalí era igual a 31°C y pasada una hora era igual a 29°C, entonces, considerando que en el instante del disparo $x = 37C$ y $a= 21C$, y tomando el instante del arresto como $t = 0$, determinar el momento del disparo.
*  (b) En el caso cuando la temperatura del aire varía con el tiempo, la ley de enfriamiento del cuerpo se convierte en la ecuación diferencial lineal no homogénea.
> $\frac{dx}{dt} = kx - ka(t)$


Donde $a(t)$ es la temperatura del aire en el instante t. Hagamos algunas conjeturas: en el instante de la detención de los sospechosos la temperatura del cuerpo del jabalí era igual a 30°C; el día del acontecimiento la temperatura del aire descendió cada hora después del medio día en 1°C y era igual a 0°C en el instante del hallazgo del cadáver; finalmente, pongamos que al cabo de una hora de ser detectado el animal, su temperatura bajó hasta 25°C. Tomando $t = 0$ como en el instante del disparo, asumiendo que entonces la temperatura corporal del jabalí era $x0 = 37C$ y denotando con t∗ el instante en que los guardabosques descubrieron el cadáver, obtenemos $a(t) = t∗ − t$.


Hallar de nuevo el momento en que murió el jabalí.



# *Solucion:*

De acuerdo al insciso **a**, tenemos que la formula de la ley de radiacion de calor es:


> $\frac{dx}{dt} = -k(x-a)$     ..............(1)


Donde x es la temperatura del cuerpo en el instante t, a es la temperatura del medio ambiente y K es un factor positivo de proporcionalidad.

Para obtener la respuesta debemos saber que al integrar no debemos olvidad que el cuerpo del jabali y la temperatura del ambiente pudo permaner invariable, por lo tanto, **al integrar a la ecuacion (1)**, tenemos:



> $\ln( \frac{x-a}{x_0 - a}) = -kt$ .......................(2)

$x \neq a$        

Para determinar el momento del disparo, comenzamos a evaluar la ecuacion 2 con los siguientes valores:


*   t=0
*   x=37°C
*   a=21°C
Tenemos que:



>**$K= \ln(\frac{31-21}{29-21}) = \ln(1.25) = 0.22314$**


Sustituimos el valor de K y x, para poder encontrar a **t** con respecto a la 2 ecuacion:

*   $K=0.22314$
*   $x=37°C$


> $t= - \frac{1}{0.22314} \ln(\frac{37-21}{31-21}) = -\frac{1}{0.22341} \ln(1.6) = -2,10630$


Por lo tanto, el instante en que se realizo el disparo y el instante en que fueron detenidos trancurrieron alrededor de **2 horas y 6 minutos.**



Con respecto al inciso **b** donde usamos la ley de radiacion de calor, la cual es:


>***$\frac{dx}{dt} +k = k a(t)$***

Tomamos en cuenta que **a(t)** es la temperatura del aire en el instante **t**.
Usamos un par de hipotesis:


1.   Cuando los sospechosos son detenidos, la temperatura del cuerpo del jabali era igual a los 30°C.
2.   Ese mismo dia, la temperatura descendia cada hora despues del medio dia en 1°C y cuando fue hallado el cuerpo era igua a 0°C.
3.   Supongamos que que al cabo de 1 hora de ser detectado el cuerpo, su temperatura bajo hasta los 25°C.

De manera que: tomando a t=0 como el instante del disparo asumimos que la temperatura del cuerpo del jabali era de x0=37°C y denotando a t* el instante en que los guardabosques descubieron el cadaver, podemos obtener:


> **$a(t)=t*-t$**

Y al integrarla, podemos observar que:



> **$x=(37 - t* - \frac{1}{k}) e ^{-kt} + t* - t + \frac{1}{k}$**

Recordamos que $x=30$ para  $t=t* $ y que $x=25$ para $t=t*+1$. Podemos obtener las igualdades de:



> $(37 - t* - \frac{1}{k}) e ^ {-k t*} + \frac{1}{k}=30$


> $(37-t*-\frac{1}{k}) e^{-k(t*+1)} + \frac{1}{k} =26 $

Y a partir de estas dos ecuadiones, podemos en contrar la ecuacion con respecto a **K**:



> $(30 - \frac{1}{k}) e ^{-k} -26 + \frac{1}{k} =0$ ..............(1)


Ahora, sabemos que la ecuacion anterior no se puede resolver con metodos algebraicos, por lo cual, podemos resolverla de una manera mas sencilla utilizando metodos numericos. Especificamente el ***metodo de Newton *** ya que parte de una estimacion inicial de raiz exacta para obtener las aproximaciones de una manera mas precisa.

Para esto, tenemos que tomar en cuenta lo siguiente:


*   Tomamos a fx como:


> $30k -1 + (1-26k)e ^{k} = 0$ .....................(2)

(Esto lo obtenemos transformando la ecuacion (1)).


*   Y $f´(x)$ como:

> $30 - 25e^{k} - 26ke^{k}$



*   Su aproximacion sera de $10^{-6}$
*   En un intervalo de $(0,1)$

Para comprobar si nuestro resultado es correcto, se utilozaran dos metodos de aproximaciones:


1.   El Metodo de Newton
2.   El Metodo de la Secante

Dichos metodos nos arrojaran la misma aproximacion.



In [ ]:
#PARA IMPLEMENTAR EL CODIGO, SE HARA UN CAMBIO DE VARIABLE DE K=X

# Método de Newton-Raphson
import numpy as np
import math

# Funcion y su derivada
fx  = lambda x: 30*x -1 +(1-26*x)*math.exp(x)
dfx = lambda x: 30-25*math.exp(x)-26*x*math.exp(x)

a=1
b=0
x0 = (a+b)/2
tolera = 0.000001

# PROCEDIMIENTO
tabla = [] #para convertirlo en lista
tramo = abs(2*tolera)
xi = x0 #El valor medio se convirtio en un valor para la sucesion. En este caso seria Pn-1
while (tramo>=tolera):
    Pn = xi - fx(xi)/dfx(xi)
    tramo  = abs(Pn-xi)
    tabla.append([xi, Pn])
    xi = Pn

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print('xi', '\tPn')
np.set_printoptions(precision = 4)
print(tabla)
print('\nRaiz en: ', xi)
print('\nError de: ',tramo)

xi 	Pn
[[0.5    0.3228]
 [0.3228 0.2282]
 [0.2282 0.1885]
 [0.1885 0.1795]
 [0.1795 0.179 ]
 [0.179  0.179 ]
 [0.179  0.179 ]]

Raiz en:  0.17895246315275215

Error de:  1.4123535674315235e-11


In [ ]:
#Metodo de la secante
import numpy as np
import math

def secante_tabla(fx,xa):
    dx = 4*tolera
    xb = xa + dx
    tramo = dx
    tabla = []
    while (tramo>=tolera):
        fa = fx(xa)#Funcion evaluada en el punto a
        fb = fx(xb)#Funcion evaluada en el punto b
        Pn = xa - fa*(xb-xa)/(fb-fa)
        tramo = abs(Pn-xa)

        tabla.append([xa,xb,Pn])
        xb = xa
        xa = Pn

    tabla = np.array(tabla)
    return(tabla)

# Funcion
#fx = lambda x: x**3 + 4*x**2 - 10
fx  = lambda x: 30*x -1 +(1-26*x)*math.exp(x)

a  = 1
b  = 0
xa = 0.5 #punto medio
#xa=0.178952
tolera = 0.001
tramos = 100


tabla = secante_tabla(fx,xa)
n = len(tabla)
raiz = tabla[n-1,2]

#Se muestra en la pantalla

np.set_printoptions(precision=4)
print('[xa ,\t xb , \t Pn]')
for i in range(0,n,1):
    print(tabla[i])
print('\nRaiz en: ', raiz)


[xa ,	 xb , 	 Pn]
[0.5   0.504 0.324]
[0.324  0.5    0.2599]
[0.2599 0.324  0.2109]
[0.2109 0.2599 0.1886]
[0.1886 0.2109 0.1805]
[0.1805 0.1886 0.179 ]
[0.179  0.1805 0.179 ]

Raiz en:  0.1789532455053561


Como vimos, ambos metodos nos arrojan el mismo valor de la raiz.

En la columna de **Pn** podemos observar las aproximaxiones de manera mas sencilla.

En este caso, el valor de su raiz es nuestra respuesta. Por lo tanto, usamos a la ecuacion (2) y despues de sustiruir a x=37 tenemos una nueva ecuacion para buscar el valor del tiempo usando ***por segunda vez el metodo de Newton y el de la Secante.***

Usamos los siguientes datos:




*   $fx = 30k -1 +(1-26k)e^{k}$   
*   $f´x= ke^{kt}-30k+1$
*   $K= 0.178952$
*   $t_0= -1$



In [ ]:


# Método de Newton-Raphson
import numpy as np
import math

# Funcion y su derivada
ft  = lambda t: (37*(0.178952) -1 +((0.178952)*t))*math.exp((0.178952)*t) -30*(0.178952)+1
dft = lambda t: (1.184881277)*math.exp((0.178952)*t)+(0.178952)*math.exp((0.178952)*t)


#a=1
#b=0
t0 = -1
#k=0.178952
tolera = 0.000001

# PROCEDIMIENTO
tabla = [] #para convertirlo en lista
tramo = abs(2*tolera)
ti = t0 #El valor medio se convirtio en un valor para la sucesion. En este caso seria Pn-1
while (tramo>=tolera):
    Pn = ti - ft(ti)/dft(ti)
    tramo  = abs(Pn-ti)
    tabla.append([ti, Pn])
    ti = Pn

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print('xi', '\tPn')
np.set_printoptions(precision = 4)
print(tabla)
print('\nRaiz en: ', ti)
print('\nError de: ',tramo)

xi 	Pn
[[-1.     -1.1596]
 [-1.1596 -1.1872]
 [-1.1872 -1.1917]
 [-1.1917 -1.1924]
 [-1.1924 -1.1925]
 [-1.1925 -1.1926]
 [-1.1926 -1.1926]
 [-1.1926 -1.1926]]

Raiz en:  -1.192561459018511

Error de:  4.588535034155683e-07


In [ ]:
#Metodo de la secante
import numpy as np
import math

def secante_tabla(fx,xa):
    dx = 4*tolera
    xb = xa + dx
    tramo = dx
    tabla = []
    while (tramo>=tolera):
        fa = fx(xa)#Funcion evaluada en el punto a
        fb = fx(xb)#Funcion evaluada en el punto b
        Pn = xa - fa*(xb-xa)/(fb-fa)
        tramo = abs(Pn-xa)

        tabla.append([xa,xb,Pn])
        xb = xa
        xa = Pn

    tabla = np.array(tabla)
    return(tabla)

# Funcion
#fx = lambda x: x**3 + 4*x**2 - 10
#fx  = lambda x: 30*x -1 +(1-26*x)*math.exp(x)
fx = lambda x: (37*(0.178952) -1 +((0.178952)*x))*math.exp((0.178952)*x) -30*(0.178952)+1

a  = 1
b  = 0
xa = -1 #punto medio
#xa=0.178952
tolera = 0.000001
tramos = 100


tabla = secante_tabla(fx,xa)
n = len(tabla)
raiz = tabla[n-1,2]

#Se muestra en la pantalla

np.set_printoptions(precision=4)
print('[xa ,\t xb , \t Pn]')
for i in range(0,n,1):
    print(tabla[i])
print('\nRaiz en: ', raiz)


# Para la Grafica
import matplotlib.pyplot as plt


[xa ,	 xb , 	 Pn]
[-1.     -1.     -1.1888]
[-1.1888 -1.     -1.1925]
[-1.1925 -1.1888 -1.1926]
[-1.1926 -1.1925 -1.1926]

Raiz en:  -1.1925615459088013


Por lo tanto, el momento en que el jabali murio fue aproximadamente **1 hora y 12 minutos o 1 hora con 19 minutos** antes de que los guardabosques lo encontraran.